TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE locations CASCADE;
TRUNCATE TABLE shops CASCADE;
TRUNCATE TABLE cafeterias CASCADE;
TRUNCATE TABLE tuckshops CASCADE;
TRUNCATE TABLE pharmacies CASCADE;
TRUNCATE TABLE bookshops CASCADE;
TRUNCATE TABLE digitalcenters CASCADE;
TRUNCATE TABLE products CASCADE;
TRUNCATE TABLE transactions CASCADE;


-- Truncate tables
TRUNCATE users RESTART IDENTITY CASCADE;
TRUNCATE locations RESTART IDENTITY CASCADE;
TRUNCATE shops RESTART IDENTITY CASCADE;
TRUNCATE cafeterias RESTART IDENTITY CASCADE;
TRUNCATE tuckshops RESTART IDENTITY CASCADE;
TRUNCATE pharmacies RESTART IDENTITY CASCADE;
TRUNCATE bookshops RESTART IDENTITY CASCADE;
TRUNCATE digitalcenters RESTART IDENTITY CASCADE;
TRUNCATE products RESTART IDENTITY CASCADE;
TRUNCATE transactions RESTART IDENTITY CASCADE;



DROP SCHEMA IF EXISTS TVET_COLLEGE_ECOMMERCE CASCADE;
CREATE SCHEMA TVET_COLLEGE_ECOMMERCE;
set search_path to TVET_COLLEGE_ECOMMERCE;
